# Generated by Django 4.2.6 on 2023-10-17 08:03

from django.db import migrations, models
import django.db.models.deletion
import telegram_messages.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("telegram_channels", "0001_initial"),
        ("clusters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("datetime", models.DateTimeField()),
                ("message_id", models.PositiveIntegerField()),
                (
                    "embedding",
                    telegram_messages.models.EmbeddingField(blank=True, null=True),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="messages",
                        to="telegram_channels.channel",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="messages",
                        to="clusters.cluster",
                    ),
                ),
            ],
            options={
                "unique_together": {("message_id", "channel")},
            },
        ),
    ]
