# Generated by Django 5.1.6 on 2025-02-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "publications",
                    models.ManyToManyField(
                        related_name="summaries", to="publications.publication"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "summaries",
            },
        ),
    ]
