# Generated by Django 4.2.6 on 2025-02-23 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("summaries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="summary",
            options={"verbose_name_plural": "summaries"},
        ),
    ]
