# Generated by Django 5.1.6 on 2025-02-23 20:32

import commons.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("channels", "0002_rename_channel_id_channel_telegram_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("datetime", models.DateTimeField()),
                ("telegram_id", models.PositiveIntegerField()),
                (
                    "embedding",
                    commons.models.EmbeddingField(blank=True, editable=False),
                ),
                ("views", models.PositiveIntegerField()),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="publications",
                        to="channels.channel",
                    ),
                ),
            ],
            options={
                "unique_together": {("telegram_id", "channel")},
            },
        ),
    ]
