# Generated by Django 4.2.6 on 2025-02-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0001_initial"),
        ("clusters", "0001_initial"),
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="publications",
                to="channels.channel",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publications",
                to="clusters.cluster",
            ),
        ),
    ]
