# Generated by Django 4.2.6 on 2025-02-22 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0002_rename_channel_id_channel_telegram_id"),
        ("publications", "0002_alter_publication_channel_alter_publication_cluster"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="message_id",
            new_name="telegram_id",
        ),
        migrations.AlterUniqueTogether(
            name="publication",
            unique_together={("telegram_id", "channel")},
        ),
    ]
