# Generated by Django 4.2.6 on 2025-02-22 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channel",
            old_name="channel_id",
            new_name="telegram_id",
        ),
    ]
